import { Activity, Gamepad2, MessageSquareText, ShieldAlert, TrendingUp, UsersRound } from 'lucide-react'
import games from '../data/games.json'
import usersData from '../data/users.json'
import AdminLayout from '../components/AdminLayout'
import { getReports, getReviews } from '../services/communityService'

export default function AdminDashboardPage() {
  const reports=getReports(); const reviews=getReviews(); const stats=[{label:'Usuarios activos',value:'12,458',delta:'+8.2%',icon:UsersRound},{label:'Juegos',value:games.length,delta:'JSON + API',icon:Gamepad2},{label:'Reseñas',value:reviews.length,delta:'+ nuevas',icon:MessageSquareText},{label:'Reportes pendientes',value:reports.filter((r)=>r.status==='pending').length,delta:'requieren revisión',icon:ShieldAlert}]
  return <AdminLayout title="Dashboard administrador" subtitle="Resumen operativo y accesos rápidos de la demostración."><div className="admin-stat-grid">{stats.map(({label,value,delta,icon:Icon})=><article key={label}><span className="admin-stat-icon"><Icon/></span><div><small>{label}</small><b>{value}</b><em>{delta}</em></div></article>)}</div><div className="admin-dashboard-grid"><section className="admin-panel chart-panel"><div className="panel-heading"><div><small>Actividad de la plataforma</small><h2>Interacciones semanales</h2></div><TrendingUp/></div><div className="fake-chart">{[42,58,51,73,66,82,76,94,89,108,102,118].map((h,i)=><span key={i} style={{height:`${h}px`}}/>)}</div><div className="chart-labels"><span>Lun</span><span>Mié</span><span>Vie</span><span>Dom</span></div></section><section className="admin-panel"><div className="panel-heading"><div><small>Estado de moderación</small><h2>Reportes</h2></div><Activity/></div><div className="donut-wrap"><div className="donut"><span>{reports.length}</span></div><ul><li>Pendientes <b>{reports.filter((r)=>r.status==='pending').length}</b></li><li>Aprobados <b>{reports.filter((r)=>r.status==='approved').length}</b></li><li>Rechazados <b>{reports.filter((r)=>r.status==='rejected').length}</b></li></ul></div></section></div><section className="admin-panel"><div className="panel-heading"><div><small>Arquitectura de datos</small><h2>Fuentes activas</h2></div></div><div className="source-grid"><span><b>Catálogo</b><small>JSON local + RAWG opcional</small></span><span><b>Comunidad</b><small>JSON + localStorage</small></span><span><b>Sesión</b><small>sessionStorage</small></span><span><b>Usuarios seed</b><small>{usersData.users.length} cuentas demo</small></span></div></section></AdminLayout>
}
