import { Award, BadgeCheck, BookOpen, Clock3, Star, ThumbsUp } from 'lucide-react'
import usersData from '../data/users.json'
import games from '../data/games.json'
import GameCard from '../components/GameCard'
import ReviewCard from '../components/ReviewCard'
import { getReviews } from '../services/communityService'

export default function CriticProfilePage() {
  const critic=usersData.users.find((u)=>u.role==='critic'); const reviews=getReviews().filter((r)=>r.userId===critic.id); const professional=reviews.filter((r)=>r.criticAnalysis); const reviewedGames=reviews.map((r)=>games.find((g)=>g.id===r.gameId)).filter(Boolean); const avg=reviews.length?(reviews.reduce((a,r)=>a+Number(r.rating),0)/reviews.length).toFixed(1):'N/D'; const hours=professional.reduce((a,r)=>a+(r.criticAnalysis?.hoursPlayed||0),0); const helpful=reviews.reduce((a,r)=>a+(r.helpful||0),0)
  return <div className="page dark-page"><section className="critic-hero"><div className="critic-avatar">AR<span><BadgeCheck/></span></div><div><span className="eyebrow">Perfil del crítico</span><h1>{critic.username}</h1><p>{critic.bio}</p><div className="tag-row"><span><Award size={15}/> Verificado</span><span><Star size={15}/> Rep. {critic.reputation}</span><span><BookOpen size={15}/> {reviews.length} análisis</span></div></div></section><section className="content-section"><div className="critic-metrics"><article><Star/><b>{avg}</b><span>Nota media</span></article><article><Clock3/><b>{hours}</b><span>Horas analizadas</span></article><article><ThumbsUp/><b>{helpful}</b><span>Votos útiles</span></article><article><BookOpen/><b>{professional.length}</b><span>Críticas estructuradas</span></article></div><div className="specialty-strip"><span className="eyebrow">Especialidades</span><div className="tag-row">{(critic.specialties||['Diseño sistémico','Narrativa','Accesibilidad']).map((item)=><span key={item}>{item}</span>)}</div></div></section><section className="content-section split-section critic-layout"><div><div className="section-heading"><div><span className="eyebrow">Últimos análisis</span><h2>Críticas publicadas</h2></div></div><div className="review-list">{reviews.map((review)=><ReviewCard review={review} key={review.id}/>)}</div></div><aside className="critic-aside"><span className="eyebrow">Método de análisis</span><h3>Evaluación estructurada en ocho criterios</h3><p>Las críticas profesionales registran plataforma, horas jugadas, estado de finalización, puntuaciones por categoría, incidencias técnicas, accesibilidad, recomendación de audiencia y transparencia sobre copias proporcionadas.</p><div className="mini-game-list">{reviewedGames.map((game)=><GameCard game={game} key={game.id}/>)}</div></aside></section></div>
}
