import { BadgeCheck, BookOpen, ClipboardCheck, MessageSquareText, Shield, Star, Trophy, UserCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import games from '../data/games.json'
import GameCard from '../components/GameCard'
import ReviewCard from '../components/ReviewCard'
import { useAuth } from '../context/AuthContext'
import { getCriticApplicationByUser, getLibrary, getReviews } from '../services/communityService'

export default function ProfilePage() {
  const { user } = useAuth(); const reviews = getReviews().filter((r) => r.userId === user.id); const library = getLibrary(user.id); const application=user.role==='user'?getCriticApplicationByUser(user.id):null; const gameList = library.map((entry) => games.find((g) => g.id === entry.gameId)).filter(Boolean); const criticReviews=reviews.filter((r)=>r.criticAnalysis); const hours=criticReviews.reduce((acc,r)=>acc+(r.criticAnalysis?.hoursPlayed||0),0)
  return <div className="page dark-page"><section className="profile-hero"><div className="profile-cover"><span className="profile-stars one"/><span className="profile-stars two"/></div><div className="profile-info"><div className="avatar giant">{user.username.slice(0,2).toUpperCase()}</div><div><span className="eyebrow">{user.role === 'critic' ? 'Crítico verificado' : user.role === 'admin' ? 'Administrador' : 'Miembro GameHive'}</span><h1>{user.username} {user.verifiedCritic && <BadgeCheck/>}</h1><p>{user.bio}</p><div className="tag-row"><span>Rep. {user.reputation}</span><span>Desde {user.joined}</span></div><div className="profile-cta-row">{user.role==='user'&&<Link className="button secondary small-button" to="/critic/apply"><UserCheck size={17}/>{application?` Solicitud: ${application.status}`:' Solicitar rol de crítico'}</Link>}{user.role==='critic'&&<Link className="button secondary small-button" to="/explore"><ClipboardCheck size={17}/> Crear nueva crítica</Link>}</div></div></div></section><section className="content-section"><div className="profile-stats"><span><Star/><b>{user.reputation}</b><small>Reputación</small></span><span><MessageSquareText/><b>{reviews.length}</b><small>{user.role==='critic'?'Críticas':'Reseñas'}</small></span><span><BookOpen/><b>{library.length}</b><small>Biblioteca</small></span><span><Trophy/><b>{user.role==='critic'?hours:reviews.reduce((acc,r) => acc+r.helpful,0)}</b><small>{user.role==='critic'?'Horas analizadas':'Votos útiles'}</small></span></div><div className="section-heading"><div><span className="eyebrow">Biblioteca pública</span><h2>Juegos recientes</h2></div></div><div className="game-grid compact-grid">{gameList.slice(0,4).map((game) => <GameCard game={game} key={game.id}/>)}</div><div className="section-heading review-heading"><div><span className="eyebrow">Contribuciones</span><h2>{user.role==='critic'?'Críticas profesionales':'Reseñas publicadas'}</h2></div></div><div className="review-list narrow">{reviews.length ? reviews.map((review) => <ReviewCard review={review} key={review.id}/>) : <div className="empty-state compact"><Shield/><h3>Aún no has publicado reseñas.</h3></div>}</div></section></div>
}
