import { CheckCircle2, ClipboardCheck, Gamepad2, Send, Star } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import games from '../data/games.json'
import GameArtwork from '../components/GameArtwork'
import { useAuth } from '../context/AuthContext'
import { saveReview } from '../services/communityService'

const SCORE_FIELDS = [
  ['gameplay', 'Jugabilidad'], ['story', 'Narrativa'], ['art', 'Arte y diseño'], ['sound', 'Sonido y música'],
  ['performance', 'Rendimiento técnico'], ['accessibility', 'Accesibilidad'], ['content', 'Contenido y duración'], ['value', 'Calidad / precio'],
]
const TECH_ISSUES = ['Bugs leves', 'Bugs graves', 'Caídas de FPS', 'Crashes', 'Problemas gráficos', 'Problemas de conexión']
const ACCESSIBILITY = ['Subtítulos', 'Tamaño de texto', 'Modo daltonismo', 'Controles configurables', 'Ayudas de navegación', 'Dificultad configurable', 'Opciones auditivas']
const AUDIENCES = ['Casual', 'Competitivo', 'Narrativa', 'Exploración', 'Multijugador', 'RPG', 'Estrategia', 'Acción']

function toggleValue(list, value) { return list.includes(value) ? list.filter((item) => item !== value) : [...list, value] }

function CommunityReviewForm({ game, user }) {
  const navigate = useNavigate(); const [rating, setRating] = useState(8); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [error, setError] = useState('')
  const submit = (e) => { e.preventDefault(); if (title.trim().length < 5 || body.trim().length < 40) return setError('Añade un título claro y al menos 40 caracteres de opinión.'); saveReview({ gameId: game.id, userId: user.id, author: user.username, role: user.role, verified: user.verifiedCritic, reputation: user.reputation, rating: Number(rating), title: title.trim(), body: body.trim() }); navigate(`/game/${game.id}`) }
  return <><section className="page-banner"><span className="eyebrow">Tu experiencia importa</span><h1>Escribe tu reseña</h1><p>La reseña comunitaria es breve y personal: una nota, contexto y tu opinión sobre el juego.</p></section><section className="content-section review-editor-layout"><main className="editor-card"><EditorGame game={game}/><form className="stack-form" onSubmit={submit}><label>Tu puntuación<div className="rating-input"><Star fill="currentColor"/><input type="range" min="1" max="10" step="0.1" value={rating} onChange={(e) => setRating(e.target.value)}/><b>{rating}/10</b></div></label><label>Título<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Resume tu impresión en una línea"/></label><label>Reseña<textarea rows="9" value={body} onChange={(e) => setBody(e.target.value)} placeholder="¿Qué funciona? ¿Qué no? ¿Para quién lo recomendarías?"/></label>{error && <div className="form-error">{error}</div>}<div className="editor-actions"><Link className="button secondary" to={`/game/${game.id}`}>Cancelar</Link><button className="button primary"><Send size={18}/> Publicar reseña</button></div></form></main><WritingGuide critic={false}/></section></>
}

function EditorGame({ game }) { return <div className="editor-game"><GameArtwork game={game}/><div><span>{game.genres.join(' · ')}</span><h2>{game.name}</h2><p>{game.tagline}</p></div></div> }

function WritingGuide({ critic }) { return <aside className="writing-guide">{critic ? <ClipboardCheck/> : <Gamepad2/>}<h3>{critic ? 'Criterios de crítica profesional' : 'Una buena reseña ayuda a decidir'}</h3><ul>{critic ? <><li><CheckCircle2/> Registra plataforma, horas y estado de finalización.</li><li><CheckCircle2/> Puntúa ocho dimensiones y justifica el análisis.</li><li><CheckCircle2/> Declara problemas técnicos, accesibilidad y copia de prensa.</li><li><CheckCircle2/> Separa puntuación calculada de tu veredicto editorial.</li></> : <><li><CheckCircle2/> Explica por qué te funcionó o no.</li><li><CheckCircle2/> Separa gusto personal de problemas técnicos.</li><li><CheckCircle2/> Evita spoilers importantes sin advertencia.</li><li><CheckCircle2/> No uses la reputación como prueba de verdad.</li></>}</ul></aside> }

function CriticReviewForm({ game, user }) {
  const navigate = useNavigate()
  const [platform, setPlatform] = useState(game.platforms?.[0] || 'PC'); const [hoursPlayed, setHoursPlayed] = useState(20); const [completedGame, setCompletedGame] = useState('yes')
  const [scores, setScores] = useState(Object.fromEntries(SCORE_FIELDS.map(([key]) => [key, 8]))); const calculatedScore = useMemo(() => Number((Object.values(scores).reduce((a,b)=>a+Number(b),0)/SCORE_FIELDS.length).toFixed(1)), [scores])
  const [finalScore, setFinalScore] = useState(8); const [technicalIssues, setTechnicalIssues] = useState([]); const [accessibility, setAccessibility] = useState([]); const [valueVerdict, setValueVerdict] = useState('Adecuado')
  const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [body, setBody] = useState(''); const [pros, setPros] = useState(''); const [cons, setCons] = useState(''); const [recommendedFor, setRecommendedFor] = useState([]); const [reviewCopyProvided, setReviewCopyProvided] = useState(false); const [scoreReason, setScoreReason] = useState(''); const [error, setError] = useState('')
  const submit = (e) => {
    e.preventDefault(); const prosList=pros.split('\n').map(v=>v.trim()).filter(Boolean); const consList=cons.split('\n').map(v=>v.trim()).filter(Boolean)
    if (Number(hoursPlayed) < 1) return setError('Indica al menos una hora de juego para contextualizar la crítica.')
    if (title.trim().length < 8 || summary.trim().length < 30 || body.trim().length < 120) return setError('La crítica profesional necesita un título, un resumen de al menos 30 caracteres y un análisis de al menos 120 caracteres.')
    if (!prosList.length || !consList.length) return setError('Incluye al menos un aspecto positivo y uno por mejorar, cada uno en una línea.')
    if (!recommendedFor.length) return setError('Selecciona al menos un tipo de jugador al que recomendarías el título.')
    if (Math.abs(Number(finalScore)-calculatedScore) >= 1 && scoreReason.trim().length < 20) return setError('Tu nota final difiere bastante del promedio. Explica brevemente el criterio editorial de la diferencia.')
    saveReview({ gameId: game.id, userId: user.id, author: user.username, role: 'critic', verified: true, reputation: user.reputation, rating: Number(finalScore), title: title.trim(), body: body.trim(), criticAnalysis: { platform, hoursPlayed:Number(hoursPlayed), completedGame, scores, calculatedScore, summary:summary.trim(), technicalIssues, accessibility, valueVerdict, pros:prosList, cons:consList, recommendedFor, reviewCopyProvided, scoreReason:scoreReason.trim() } })
    navigate(`/game/${game.id}`)
  }
  return <><section className="page-banner critic-review-banner"><span className="eyebrow">Crítica verificada</span><h1>Crear análisis profesional</h1><p>Tu rol de crítico exige más contexto que una reseña comunitaria. Documenta la experiencia, evalúa criterios y construye un veredicto argumentado.</p></section><section className="content-section review-editor-layout"><main className="editor-card critic-editor"><EditorGame game={game}/><form className="stack-form" onSubmit={submit}>
    <div className="critic-form-section"><div className="form-section-heading"><span>01</span><div><h3>Contexto de la experiencia</h3><p>Ayuda a entender desde dónde se construye tu crítica.</p></div></div><div className="form-grid three"><label>Plataforma<select value={platform} onChange={(e)=>setPlatform(e.target.value)}>{game.platforms?.map((p)=><option key={p}>{p}</option>)}</select></label><label>Horas jugadas<input type="number" min="1" max="999" value={hoursPlayed} onChange={(e)=>setHoursPlayed(e.target.value)}/></label><label>Estado<select value={completedGame} onChange={(e)=>setCompletedGame(e.target.value)}><option value="yes">Completado</option><option value="partial">Parcialmente completado</option><option value="no">No completado</option></select></label></div></div>
    <div className="critic-form-section"><div className="form-section-heading"><span>02</span><div><h3>Evaluación por categorías</h3><p>Ocho criterios separados evitan que una sola impresión domine la nota.</p></div></div><div className="score-question-grid">{SCORE_FIELDS.map(([key,label])=><label className="score-question" key={key}><span>{label}<b>{Number(scores[key]).toFixed(1)}</b></span><input type="range" min="1" max="10" step="0.5" value={scores[key]} onChange={(e)=>setScores({...scores,[key]:Number(e.target.value)})}/></label>)}</div><div className="calculated-score"><span>Promedio calculado</span><b>{calculatedScore}/10</b><small>Referencia matemática, no reemplaza el criterio editorial.</small></div></div>
    <div className="critic-form-section"><div className="form-section-heading"><span>03</span><div><h3>Control técnico y accesibilidad</h3><p>Registra problemas observados y herramientas disponibles durante el análisis.</p></div></div><p className="field-title">Problemas técnicos encontrados</p><div className="check-grid">{TECH_ISSUES.map((v)=><label className="check-card" key={v}><input type="checkbox" checked={technicalIssues.includes(v)} onChange={()=>setTechnicalIssues(toggleValue(technicalIssues,v))}/><span>{v}</span></label>)}</div><p className="field-title">Opciones de accesibilidad verificadas</p><div className="check-grid">{ACCESSIBILITY.map((v)=><label className="check-card" key={v}><input type="checkbox" checked={accessibility.includes(v)} onChange={()=>setAccessibility(toggleValue(accessibility,v))}/><span>{v}</span></label>)}</div><label>Relación calidad / precio<select value={valueVerdict} onChange={(e)=>setValueVerdict(e.target.value)}><option>Muy insuficiente</option><option>Insuficiente</option><option>Adecuado</option><option>Bueno</option><option>Excelente</option></select></label></div>
    <div className="critic-form-section"><div className="form-section-heading"><span>04</span><div><h3>Argumento editorial</h3><p>Convierte las puntuaciones en una crítica legible y defendible.</p></div></div><label>Título<input value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Una tesis breve sobre el juego"/></label><label>Resumen editorial<textarea rows="3" value={summary} onChange={(e)=>setSummary(e.target.value)} placeholder="Síntesis de la crítica para lectura rápida"/></label><label>Análisis completo<textarea rows="10" value={body} onChange={(e)=>setBody(e.target.value)} placeholder="Analiza sistemas, narrativa, arte, sonido, técnica, accesibilidad y valor. Evita convertirlo en una lista de gustos personales."/></label><div className="form-grid two"><label>Aspectos positivos <small>Uno por línea</small><textarea rows="5" value={pros} onChange={(e)=>setPros(e.target.value)} placeholder={'Dirección artística\nDiseño de combate'}/></label><label>Aspectos por mejorar <small>Uno por línea</small><textarea rows="5" value={cons} onChange={(e)=>setCons(e.target.value)} placeholder={'Rendimiento irregular\nMisiones repetitivas'}/></label></div></div>
    <div className="critic-form-section"><div className="form-section-heading"><span>05</span><div><h3>Veredicto y transparencia</h3><p>Define a quién se lo recomendarías y declara el origen de la copia analizada.</p></div></div><p className="field-title">Recomendado para</p><div className="check-grid audience-grid">{AUDIENCES.map((v)=><label className="check-card" key={v}><input type="checkbox" checked={recommendedFor.includes(v)} onChange={()=>setRecommendedFor(toggleValue(recommendedFor,v))}/><span>{v}</span></label>)}</div><div className="final-score-box"><label>Puntuación final<input type="number" min="1" max="10" step="0.1" value={finalScore} onChange={(e)=>setFinalScore(e.target.value)}/></label><div><span>Promedio por categorías</span><b>{calculatedScore}/10</b></div></div><label>Justificación si modificas sustancialmente el promedio<textarea rows="3" value={scoreReason} onChange={(e)=>setScoreReason(e.target.value)} placeholder="Opcional salvo que tu nota final se aleje 1 punto o más del promedio calculado."/></label><label className="declaration-check"><input type="checkbox" checked={reviewCopyProvided} onChange={(e)=>setReviewCopyProvided(e.target.checked)}/><span>Recibí gratuitamente una copia del juego para realizar esta crítica. Esta declaración se mostrará públicamente.</span></label></div>
    {error && <div className="form-error">{error}</div>}<div className="editor-actions"><Link className="button secondary" to={`/game/${game.id}`}>Cancelar</Link><button className="button primary"><Send size={18}/> Publicar crítica profesional</button></div>
  </form></main><WritingGuide critic/></section></>
}

export default function ReviewEditorPage() {
  const { gameId } = useParams(); const game = games.find((g) => g.id === gameId); const { user } = useAuth()
  if (!game) return <div className="page dark-page"><div className="empty-state tall"><h1>Juego no encontrado</h1></div></div>
  return <div className="page dark-page">{user.role === 'critic' ? <CriticReviewForm game={game} user={user}/> : <CommunityReviewForm game={game} user={user}/>}</div>
}
